services:
  postgres:
    image: postgres:16-alpine
    container_name: banking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking_db
    ports:
      - "5433:5432"
    volumes:
      - banking_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./banking-backend
    container_name: banking-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  frontend:
    build: ./banking-frontend
    container_name: banking-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  banking_postgres_data:
